# Generated by Django 5.1.2 on 2024-11-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_add_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
