# Generated by Django 5.1.2 on 2024-12-03 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='leave_Master',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='leave_emp_assign',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment3.employee')),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment3.leave_master')),
            ],
        ),
        migrations.CreateModel(
            name='leave_apply',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_leave', models.DateField(default=django.utils.timezone.now)),
                ('no_of_apply_leave', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment3.employee')),
                ('leave_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment3.leave_emp_assign')),
            ],
        ),
    ]
