# Generated by Django 5.1.2 on 2024-12-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chapter",
            fields=[
                ("chapter_id", models.AutoField(primary_key=True, serialize=False)),
                ("chapter_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=500)),
                ("option1", models.CharField(max_length=100)),
                ("option2", models.CharField(max_length=100)),
                ("option3", models.CharField(max_length=100)),
                ("option4", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                (
                    "chapter_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faculty.chapter",
                    ),
                ),
                (
                    "subject_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faculty.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="subject_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faculty.subject"
            ),
        ),
    ]
