# Generated by Django 5.1.2 on 2024-12-16 11:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Book',
            fields=[
                ('ISBN_No', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=100)),
                ('Author_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='user',
        ),
        migrations.CreateModel(
            name='Book_Issued',
            fields=[
                ('Book_Issued_id', models.AutoField(primary_key=True, serialize=False)),
                ('Issued_Date', models.DateField(default=datetime.date.today)),
                ('mobile', models.CharField(max_length=10)),
                ('Book_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.add_book')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookIssue',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
