# Generated by Django 4.2 on 2024-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment4', '0002_product_delete_productmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
