# Generated by Django 4.2 on 2024-12-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment4', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
