# Generated by Django 5.1.2 on 2024-11-22 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(default=django.utils.timezone.now)),
                ('prodID', models.IntegerField()),
                ('prodRate', models.IntegerField()),
                ('orderQty', models.IntegerField()),
                ('orderValue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Master',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=30)),
                ('prodRate', models.CharField(max_length=30)),
                ('prodQty', models.CharField(max_length=30)),
            ],
        ),
    ]
