# Generated by Django 5.1.2 on 2024-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
