# Generated by Django 5.1.2 on 2024-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_master',
            name='id',
        ),
        migrations.AlterField(
            model_name='register_master',
            name='email',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
